version: "3.0"
services:
  lrv10-backend:
    build:
      args:
        user: ahmad
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lrv10-be-image
    container_name: lrv10-be
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lrv10-network

  db:
    image: mysql:5.7.42
    container_name: lrv10-db
    restart: unless-stopped
    ports:
      - 3309:3306
    environment:
      MYSQL_HOST: lrv10-db
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PORT: ${DB_PORT}
      PMA_HOST: mysql
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - lrv10-network

  nginx:
    image: nginx:alpine
    container_name: lrv10-nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lrv10-network

networks:
  lrv10-network:
    driver: bridge